### ISSUE TITLE
Install script not working for UEFI boot

### ISSUE THREAD

**Issue by koallen** [lfelipe1501/Atomic-GRUB2-Theme#3]
I'm using Fedora 28. When running the installation script, it generates grub.cfg to `/boot/grub2/grub.cfg`. However, as I'm booting with UEFI, the correct location is `/boot/efi/EFI/fedora/grub.cfg`.

The script should be updated to check this or give the user a warning etc.

**Comment by lfelipe1501** [comment]
mmmm, but this depend of your installation of grub in this case if you personalize the path of the config file you need adjust manually the theme in your grub config.

in the same way we are going to add this in the installation file so that the user has it in mind when installing that the script is for the default installation of grub and its configuration file

**Comment by lfelipe1501** [comment]
#8
